Update ToolCallingAgent model initialization
While running the agent with the default model configuration, the following error is raised:

AgentGenerationError: Error while generating output:
(Request ID: Root=1-6916f94a-5dc4b9c97e16bf90732e59b9;9c212a85-b582-424c-8807-a865b3a534cc)

Bad request:
{'code': '400', 'error_type': 'INVALID_TOOL_CHOICE', 'message': 'Supported tool_choice values are "auto" and "none" currently.', 'param': 'tool_choice'}

The issue is caused by the fact that Qwen Coder models do not support tool/function calling.